PUT http://localhost:3001/api/blogs/64c7afc4c7528d8854c107a2
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6InJvb3QiLCJpZCI6IjY0YzdhODg0YjVhMzcyZDQ5Njc0OTA5NCIsImlhdCI6MTY5MDgwODAwNX0.FvzsDtc2gqlo5Eopt74_L9hKy05RJ_A_IUWmnZL3wDw

{
  "title": "The Journey of Coding 2",
  "author": "CodeMaster",
  "url": "example.com/coding-journey",
  "likes": 23
}